### ISSUE TITLE
prevailing issue, NodeMCU: "assert failed: ledc_clk_cfg_to_global_clk ledc.c:443"

### ISSUE THREAD

**Issue by MM-112211** [marcelstoer/marcelstoer#1]
Hello, I'm sorry I'm new to github and didn't know where else this issue could have been posted to be accesible to relevant people.

I recently purchased a "ESP32S NodeMCU Module WLAN WiFi Dev Kit C" from AZ-Delivery and am trying to run a OV7670-Cam on it via instructions and code from the following project "https://github.com/bitluni/ESP32CameraI2S". 

Pin-Setups and Code are unchanged for me but i get the error message as described in your issue from Nov 11, 2022 (https://github.com/nodemcu/nodemcu-firmware/issues/3558):

``` assert failed: ledc_clk_cfg_to_global_clk ledc.c:446 (false)  ```

followed by a device-reset. 
The breaking point seems to be the following line in setup (point of failure found through Serial.print- commands before and after):

```camera = new OV7670(OV7670::Mode::QQVGA_RGB565, SIOD, SIOC, VSYNC, HREF, XCLK, PCLK, D0, D1, D2, D3, D4, D5, D6, D7);```

The issue I have is, that the esp32 library for arduino doesn't even seem to contain a ledc.c file anymore, so i couldn't modify anything there. The most recent version of the nodemcu-firmware also doesn't seem to contain the file anymore.

So my questions are, 
- if this issue could be related to a old version of the firmware beeing present on my device
- if the issue might arrise due to the cam-tutorial beeing outdated, or 
- what other causes there could be 

help would be greatly appreceated. I apologize again for the direct issue submission.

**Comment by marcelstoer** [comment]
--> https://esp32.com/
